---

##
# This file is part of the `src-run/arthur-doctrine-exception-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
# (c) Scribe Inc      <scr@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

sudo     : false
language : php
php      : [ 7.1, 7.2, nightly ]

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

git:
  depth : 3

env :
  global :
    - secure: "gi0z/w7iaqtz0iNlVuVPDGQryZVkbQ/vltSa6aPbVumq7UJtdpGIbUYTVNvtjE4HXVYPvfLRfPTByGfsXoQ6WzROVXNhi85Hp2sIeQOAuJnwr2/1tjeCdgSVU0hEHDLQ8rs7Fo/SphnzxvyCIwoLDgUTiZdX+uaO0cGH2dRrRUKWVY3kEMrpD3mIKaWlKkBNsRDeBKKMRMu9wkhqGMzMVhnD/1hAj4AB8Npvi33RwKci+cYdGWw7YqjtneCzVsI/qW2v82DWgc3n6uOFZtcMW+LeUM+xOgwJ7b5R78zirm2vLFk5UOQHqM5hzxsneIWG1OsDiVAds9tyBIYlEKIR6qQTOnrqbkUzZMMJ33f7IJYyYgMPxZPZjdTqfMWTA91jYEf3Th/Mo6QeXgwIOnSgZOgQjbIH+Yz5xZDIJrMm1N7ncKH0h+RDDDoil3VuRHzHpxOOUDTy8P5qfny5FWP3fYNvcKcvPFbAjN8k+rcKY4uhVzNltDnmP/JX2HkD3B/FCchmVdtcIG//U84MbeOJbteEPsU8s+FpsEfv6t/Cv3hdVucPwdifaRm29//zzvVijdwQ99zWo/epvKl4Fpq+mfbmeMKT6sOoqW6hgbyZoyGn2bzEvwaaNSySY1MXLVrpvV3CTIlrFhf4vT7k6/4w+EomemfWOxLeswFXE+AxBAc="

install :
  - bash .bldr/bldr -b up

script :
  - bin/simple-phpunit || bin/phpunit

after_script :
  - bash .bldr/bldr -b down

...
