---

##
# This file is part of the `src-run/arthur-doctrine-exception-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
# (c) Scribe Inc      <scr@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

sudo     : false
language : php
php      : [ 5.6, 7.0 ]

git:
  depth : 3

env :
  global :
    - secure : A+E+w/lpinxctMolo6uU5WXfb0+jyeNMiyCcxilsTkEptFUWRphqLjjWqdM/pVnga/2ADtj615iNqHObefZ+/DGTRTSa/N5pHWKuzQIs0ea/OLejtGbA0JD9/30rZF+ylBGOAGCmEkVEOFGKus40YUz39lnUczBSuBm2+GHfD0+Z2J45Dnd4uGslocI4ypgxkVH+0cP/sT4OBTWTeLFZaw5fy41pVcg7riGd4miPu8I4FX3T6JlmXTSRqvrqdRg61jEx1v1PaZfM8729f3VxIFNLx7hbO0RwH+ySMJPESXXvJiULFQGBukuf+n3eMR6tjfKq0x4BTZdLX64GHYaKTuEcdcJsVs1B/v6dc9vm3ZItnrvf7rnksL57OPkN3qBMSNWIw6sYt81aBXjsYTZng/sD2Q8BNtzbNz/EyKpDT4dp7aNpcl9tRVDADuNbE8jNN0qRYMjsrYYEQlKh80a5LQ00nHITJYdVCMLcaKnnkyjhsB4ymB2rsg/s/1pvW3KCJ5CKiykXMBzXyXAfOnr7ZMvRSWcypLdiNRUUTo7cC6pZoRqCtwgRipU67sZnRMReKEHb3HLT05ETfwLKRs1QVdEqnHSWdNCchcmnNGA9ou2rWMYAP7mRT5N7xh3oGBIf824zAWsjCV0W8n5a5F3DHRtrBn4+11OnCrHu92DNBrY=

install :
  - bash .bldr/bldr -b up-env -q
  - bash .bldr/bldr -b up-app -q

script :
  - bin/phpunit -vvv

after_script :
  - bash .bldr/bldr -b down-app -q
  - bash .bldr/bldr -b down-env -q

...
